version: '3.7'

services:
  app-traefik:
    image: traefik:1.7.2-alpine
    container_name: traefik
    labels:
      - traefik.frontend.rule=Host:monitor.agrobiotech.frogydev.com.mx
      - traefik.port=8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - ./traefik.toml:/traefik.toml:Z
      - ./acme.json:/acme.json:Z
    networks:
      - app
networks:
  app:
    external: true
    name: app